apiVersion: apps/v1
kind: Deployment
metadata:
  name: capg-controller-manager
  namespace: capg-system
spec:
  template:
    spec:
      containers:
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          #value: /home/.gcp/credentials.json
          $patch: delete
        name: manager
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - $patch: delete
          #mountPath: /home/.gcp
          name: credentials
      volumes:
      - name: credentials
        $patch: delete
        # secret:
        #   secretName: manager-bootstrap-credentials