name: 'Tag Release'

on:
  push:
    branches:
      - master
      - 'release-*'
    paths:
      - kops-version.go

jobs:
  tag-release:
    if: ${{ github.repository == 'kubernetes/kops' }}
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/tag-release.sh
